### ISSUE TITLE
Consider adding config component

### ISSUE THREAD

**Issue by ssnepenthe** [ssnepenthe/soter-command#8]
Could be stored in the options table or maybe better as a file under ~/.wp-cli.

Primary goal would be to allow user to override defaults for command options:

Would need add, remove, set and unset commands to go with it.

**Comment by ssnepenthe** [comment]
I think it should be possible to grab configuration from any of the config files allowed by WP-CLI...

**Comment by ssnepenthe** [comment]
Better yet -

WP-CLI allows defaults to be set on a per-command basis in config files which means this is not needed.

Example for `wp-cli.yml`:

```yaml
soter check-site:
  fields: id,vuln_type,fixed_in
  ignore: custom-plugin,custom-theme
```
